// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEPATechDotnetCoreMVC.Data;

namespace NEPATechDotnetCoreMVC.Migrations
{
    [DbContext(typeof(NEPATechDbContext))]
    [Migration("20180531191715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NEPATechDotnetCoreMVC.Models.ContactLog.ContactLog", b =>
                {
                    b.Property<int>("ContactLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Message")
                        .IsRequired();

                    b.HasKey("ContactLogId");

                    b.ToTable("ContactLogs");
                });

            modelBuilder.Entity("NEPATechDotnetCoreMVC.Models.MemberProfile.MemberProfile", b =>
                {
                    b.Property<int>("MemberProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Biography");

                    b.Property<DateTime>("LastActive");

                    b.Property<int>("UserId");

                    b.HasKey("MemberProfileId");

                    b.ToTable("MemberProfiles");
                });

            modelBuilder.Entity("NEPATechDotnetCoreMVC.Models.Project.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProjectDesc")
                        .IsRequired();

                    b.Property<string>("ProjectLink")
                        .IsRequired();

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("UserId");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NEPATechDotnetCoreMVC.Models.Skill.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("UserId");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
